version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root