version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /app
    # app.py를 통해 주피터를 실행하도록 변경
    command: python app.py